In [1]:
import numpy as np


np.random.randint(1, 100, (4,2))


array([[45, 61],
       [71, 52],
       [70, 68],
       [82, 43]])

In [3]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [4]:
big_arr = np.random.randint(1, 10, 100)

In [5]:
grid_arr = big_arr.reshape(10, 10)

In [6]:
grid_arr


array([[8, 3, 1, 4, 3, 1, 6, 8, 5, 4],
       [8, 8, 5, 1, 8, 4, 1, 5, 4, 3],
       [5, 1, 8, 8, 1, 4, 8, 1, 3, 5],
       [6, 7, 6, 1, 8, 2, 7, 8, 5, 2],
       [3, 1, 8, 1, 6, 7, 7, 6, 4, 3],
       [5, 6, 2, 1, 3, 8, 4, 5, 9, 4],
       [8, 2, 6, 6, 3, 7, 8, 2, 8, 2],
       [9, 4, 8, 1, 1, 1, 1, 5, 1, 3],
       [3, 3, 3, 4, 1, 4, 3, 3, 5, 8],
       [1, 7, 1, 8, 3, 4, 4, 5, 5, 5]])

In [7]:
grid_arr.max()

9

In [8]:
grid_arr.min()

1

In [9]:
grid_arr.argmax()

58

In [10]:
grid_arr.argmin()

2

In [12]:
grid_arr.shape

(10, 10)

In [13]:
arr = np.array([1, 4, 6, 78, 9])

In [14]:
arr


array([ 1,  4,  6, 78,  9])

In [15]:
from numpy.random import randint

randint(4)

3

In [6]:

arr = np.arange(1, 51).reshape(10, 5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [9]:
arr[3:8, 2:5]

array([[18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40]])

In [10]:
arr[arr < 20]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
arr ** 2

array([[   1,    4,    9,   16,   25],
       [  36,   49,   64,   81,  100],
       [ 121,  144,  169,  196,  225],
       [ 256,  289,  324,  361,  400],
       [ 441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225],
       [1296, 1369, 1444, 1521, 1600],
       [1681, 1764, 1849, 1936, 2025],
       [2116, 2209, 2304, 2401, 2500]])

In [12]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978],
       [6.        , 6.08276253, 6.164414  , 6.244998  , 6.32455532],
       [6.40312424, 6.4807407 , 6.55743852, 6.63324958, 6.70820393],
       [6.78232998, 6.8556546 , 6.92820323, 7.        , 7.07106781]])

In [13]:
np.exp(arr[arr < 20])

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [14]:
np.max(arr ** 2)

2500

In [15]:
arr.max()

50

In [16]:
arr2 = np.arange(0, 50)

In [17]:
arr2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
arr2 / arr2

C:\Users\philm\AppData\Local\Temp\ipykernel_20896\3053098687.py:1: RuntimeWarning: invalid value encountered in divide
  arr2 / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [19]:
1 / arr2

C:\Users\philm\AppData\Local\Temp\ipykernel_20896\3854864060.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667,
       0.04      , 0.03846154, 0.03703704, 0.03571429, 0.03448276,
       0.03333333, 0.03225806, 0.03125   , 0.03030303, 0.02941176,
       0.02857143, 0.02777778, 0.02702703, 0.02631579, 0.02564103,
       0.025     , 0.02439024, 0.02380952, 0.02325581, 0.02272727,
       0.02222222, 0.02173913, 0.0212766 , 0.02083333, 0.02040816])

In [22]:
arr2.reshape(5, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [27]:
arr2_sub = arr2.reshape(5, 10)

arr_filter =  arr2_sub[:, 5:6]

arr_filter + 100

array([[105],
       [115],
       [125],
       [135],
       [145]])

In [36]:
arr2_sub

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [34]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [32]:
arr_filter = arr_filter + 1000

In [33]:
arr_filter

array([[1005],
       [1015],
       [1025],
       [1035],
       [1045]])

In [38]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [39]:
np.sum(arr, axis=0) # Sum by column

array([235, 245, 255, 265, 275])

In [40]:
np.sum(arr, axis=1) # Sum by row

array([ 15,  40,  65,  90, 115, 140, 165, 190, 215, 240])